// <auto-generated />
namespace Recuiter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ApplicantDocument : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplicantDocument));
        
        string IMigrationMetadata.Id
        {
            get { return "201811301302536_ApplicantDocument"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
